### PR TITLE
feat!: add support for pushing helm charts to ecr

### PR DESCRIPTION
**Pull request by bmbferreira**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues
ECR supports pushing helm charts, however this is not possible with this orb yet. 
This PR adds support to also push helm charts since we need to do it in our team.

### Description

I did a breaking change in this PR because I renamed the `ecr-login` command to `docker-ecr-login` in order to be able to separate it explicitly from the new command that I added for helm, named `helm-ecr-login`.

### CODE REVIEW

**Comment by KyleTryon** [comment]
Hello @bmbferreira Thank you for this fantastic submission. This particular orb needs some small quality of life improvements to it's outdated CI pipeline before I can successfully merge this change. We will get on this immediately and report back. I don't _think_ it will cause conflicts but there may be some small required changes.

**Comment by KyleTryon** [comment]
Apologies @bmbferreira would you be able to rebase your branch? We have updated the pipeline to properly accept your change.

**Comment by bmbferreira** [comment]
> Apologies @bmbferreira would you be able to rebase your branch? We have updated the pipeline to properly accept your change.

@KyleTryon just rebased it! if you need any more changes please let me know. Thanks!

**Comment by terramauthe** [comment]
@KyleTryon - Is it possible to resurrect this PR? I'd like to make use of this helm support. I was thinking of opening a PR, but I found this PR and it looks like exactly what I'd have done. Thanks! Take care <3

**Comment by terramauthe** [comment]
Maybe @felicianotech can help? 🙏🏼 

I'm noticing there's a lot of open PRs going stale in a lot of orb repos actually. The community is opening a lot of PRs but they seem to be going to `/dev/null` 🤔

**Pull request closed without merging**
