### PR TITLE
fix/add-builder-name

### PR DESCRIPTION
**Pull request by brivu**
This `PR` adds the an explicit `builder-name` to the `docker buildx builder` used to build multi-architecture images. 

Specifying the `docker buildx builder` name enables the use of **`Docker Layer Caching`** for multi-architecture builds with `docker buildx`. Users are now able to build and image with multiple `platforms` with `DLC` enabled.

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:bb741628df7ef3abbffc55490954ed281b6839a5

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:bd4995a24f618bc704f9c2ef50c67e1c3e2a0d02

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:e4227e354281648d6e5585c3c2d913cb12d156ae

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:cc7fdaffea87ff344c4a421384a0f1c7faa74f67

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:78b3a1a328f60f67770a6f54d8bbde4742548568

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:77ef32133e0b8e2305f093559b556b831d80e5dc

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:4dfad0d6bea9d20322e2c4c749237884c36e6181

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:05eb013f052e29ff9f71566bd0bf62eb8955b74a

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:d9473df29615d4a180930c7c91a3632289a745b9

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:1cc6a3744fd9b90b649040954e9911cc88520808

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:9b952b75ce7c54f678d0470d2809710957876f0f

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:73bad4e914b6d420256c49f26e2fda62afff4012

**Review by EricRibeiro — APPROVED** [review]
LGTM

**Comment by swiknaba** [comment]
@brivu any chance we can get a release that includes this patch? Version 8.x is still unusable due to this bug if you require more than 1 build arg for docker. Thanks 🙇

**Pull request merged**
