### PR TITLE
fix: allow multiple runs of the command in the same job

### PR DESCRIPTION
**Pull request by pepesenaris**
### Checklist

- [ ] All new jobs, commands, executors, parameters have descriptions
- [ ] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### Motivation, issues

Solves https://github.com/CircleCI-Public/aws-ecr-orb/issues/233

### Description

Checks if the docker context already exists to avoid a failure when running the command twice in the same job.

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:18035b6c57fc0dd304df5f49ef87610ccc654802

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:86e04a63918154fd3f04c620104d3025ad3b22ee

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:957181d71143385abb6c60893ba25fdd6eebbdc4

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:a0c8608db8d37d15ab1335b197f268f29e37472a

**Comment by jnovick** [comment]
Has this fix been released yet?

**Pull request merged**
