### PR TITLE
fix: docker layer caching with docker buildx

### PR DESCRIPTION
**Pull request by brivu**
This `PR` fixes the `Docker Layer Caching` issue with the use of `docker buildx`. `DLC` only works when there is no `docker context` being used to build an image. This means that `DLC` will work with any platform as long as it's being built one at a time. 

If more than one `platform` is provided (i.e. `arm64`, `amd64`, etc ) , the `builder context` will be used to support multi-architecture image builds. However, **`DLC` is not currently supported if more than `platform` is provided.**

### CODE REVIEW

**Review by EricRibeiro — COMMENTED** [review]
A couple of suggestions:

- You can reduce repetition by turning the conditional argument into a variable. Notice the `context_arg` variable in the example below.
- Wrap the final command in `set -x` and `set +x`. This makes it super easier to see what runs in these heavily parameterized commands.

```bash
context_arg=""
if [ "${number_of_platforms}" -gt 1 ]; then

  if ! docker context ls | grep -q builder; then
    # We need to skip the creation of the builder context if it's already present
    # otherwise the command will fail when called more than once in the same job.
    docker context create builder
    docker run --privileged --rm tonistiigi/binfmt --install all
    docker --context builder buildx create --use
  fi
  
  context_arg="--context builder"
  echo -e "\n \n WARNING: Docker Layer Caching is currently not supported for multi-architecture image builds. \n \n"
fi

set -x
docker $context_arg buildx build \
  -f "${ORB_EVAL_PATH}"/"${ORB_VAL_DOCKERFILE}" \
  ${docker_tag_args} \
  --platform "${ORB_VAL_PLATFORM}" \
  --progress plain \
  "$@" \
  "${ORB_EVAL_PATH}"
set +x
```

Alternatively, if you want to get extra fancy, you can leverage parameter expansion:

```bash
if [ "${number_of_platforms}" -gt 1 ]; then

  if ! docker context ls | grep -q builder; then
    # We need to skip the creation of the builder context if it's already present
    # otherwise the command will fail when called more than once in the same job.
    docker context create builder
    docker run --privileged --rm tonistiigi/binfmt --install all
    docker --context builder buildx create --use
  fi
  
  context_arg="--context builder"
  echo -e "\n \n WARNING: Docker Layer Caching is currently not supported for multi-architecture image builds. \n \n"
fi

set -x
docker \
  ${context_arg:+"$context_arg"} \
  buildx build \
  -f "${ORB_EVAL_PATH}"/"${ORB_VAL_DOCKERFILE}" \
  ${docker_tag_args} \
  --platform "${ORB_VAL_PLATFORM}" \
  --progress plain \
  "$@" \
  "${ORB_EVAL_PATH}"
set +x
```

**Comment by brivu** [comment]
Thanks for the suggestions @EricRibeiro! I really like the expansion at runtime. That's really slick!

However, I've tried our your suggestion but it doesn't seem to work with this command. Using `${context_args:+"$context_args"}` gives me the following error:

```
unknown flag: --context builder
See 'docker buildx build --help'.
```

I've also tried using just `$context_args` in the `docker buildx` command without quotations and it still doesn't like it: 

```
error: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.
```

I tried to do the runtime expansion with `docker_tag_args` and it doesn't work as well. Interestingly though, that variable has to be unquoted for it to work. 

I'm adding `set +x` though. Thank you!

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:fe5a7db8448c601d36371254e96ba47468f89cc8

**Comment by brivu** [comment]
Hey @EricRibeiro, 

After some more testing, I finally got it to work with the code below. Thanks again for your suggestions!

``` 
 set -x
  docker \
    ${context_args} \
    buildx build \
    -f "${ORB_EVAL_PATH}"/"${ORB_VAL_DOCKERFILE}" \
    ${docker_tag_args} \
    --platform "${ORB_VAL_PLATFORM}" \
    --progress plain \
    "$@" \
    "${ORB_EVAL_PATH}"
  set +x
```

-Brian

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:e0ee5704fa4746ce6129c70344ced37a73dbb270

**Review by EricRibeiro — APPROVED** [review]
Great work!

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:2b2d94689a35f2e963514747d86c60bd253c5dbf

**Review by KyleTryon — APPROVED** [review]

**Pull request merged**
