### PR TITLE
Multiarch builds

### PR DESCRIPTION
**Pull request by amioranza**
### Checklist

- [ X ] All new jobs, commands, executors, parameters have descriptions
- [ X ] Examples have been added for any significant new features
- [ ] README has been updated, if necessary

### Motivation, issues

As AWS is promoting Graviton2 processors and now ECS on Fargate support it, having an option to build and push multiarch container images is an interesting option.

### Description

This change add the `platform` parameter to `build-and-push-image` job and to `build-and-push-image` and `build-image` commands. It uses `docker buildx` command instead of `docker build`.

### CODE REVIEW

**Comment by Quantisan** [comment]
@felicianotech @KyleTryon anything we can do to help get this merged?

**Comment by amioranza** [comment]
Today I finished testing it on my private env, I'll update de PR and ask for review/approval

**Comment by amioranza** [comment]
PR updated with the working version, tested to build intel and arm images of `fluentbit`. This new method uses `buildx` which requires docker version 19+.

@KyleTryon and  @felicianotech may you review it?

Thanks

**Comment by amioranza** [comment]
Hey @iynere @felicianotech @kyletryon may you check the integration tests? it is using the `--compress` option which is not valid for `docker buildx`. I commited a fix to remove the extra `\` character at the end of the command line.

**Comment by KyleTryon** [comment]
Hey @amioranza just wanted to let you know I see your comment. We're going through our rotations and Ill get to this asap. Thank you🙏

**Comment by BlakeHyde** [comment]
@KyleTryon Do you have any estimate of when this will land in a released version?

**Comment by KyleTryon** [comment]
@BlakeHyde The time has come! Getting this done ASAP

**Comment by brivu** [comment]
Hey Everyone! 

This issue has been addressed and merged in this PR: https://github.com/CircleCI-Public/aws-ecr-orb/pull/172

Cheers! 
Brian

**Pull request closed without merging**
