### PR TITLE
fix: v8.1.2

### PR DESCRIPTION
**Pull request by brivu**
## Issues addressed on patch update

- #194
- #189 
- #191

### CODE REVIEW

**Review by KyleTryon — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:c28c3f650189ae6ac48fe396bf5923c705483b5b

**Comment by zbroniszewski** [comment]
@brivu @KyleTryon I'm not able to find where these changes fix [role-arn not interpolating value from project environment variable #194](https://github.com/CircleCI-Public/aws-ecr-orb/issues/194)

In fact, I am still experiencing the same issue:
`Parameter validation failed:
Invalid length for parameter RoleArn, value: 17, valid min length: 20`

**Comment by zbroniszewski** [comment]
> @brivu @KyleTryon I'm not able to find where these changes fix [role-arn not interpolating value from project environment variable #194](https://github.com/CircleCI-Public/aws-ecr-orb/issues/194)
> 
> In fact, I am still experiencing the same issue: `Parameter validation failed: Invalid length for parameter RoleArn, value: 17, valid min length: 20`

Apologies, I do see the fix on the aws-cli-orb here: https://github.com/CircleCI-Public/aws-cli-orb/pull/108

Though it doesn't seem like aws-ecr-orb 8.1.2 is using aws-cli-orb 3.1.1 (It defines `aws-cli@3.1`, and I'm not sure if that automatically includes the latest patch?)

**Comment by lucapino-kobalt** [comment]
same issue here, it looks like this version was built the day before `aws-cli@3.1.1` came out, so those changes for the env var based role-arn do not seem to have made it in. 

I suppose a new release should just pick the latest patch, thanks to the semantic versioning. @KyleTryon @brivu can we have a new patch release of this orb, to pick up the other orb changes? do we need to create another issue for https://github.com/CircleCI-Public/aws-ecr-orb/issues/194 ?

**Pull request merged**
