### PR TITLE
[semver:patch] Add profile-name to skip-when-tags-exist describe-images call

### LINKED ISSUE #126: skip-when-tags-exist does not use profile-name parameter
### Orb version

```
aws-ecr: circleci/aws-ecr@6.15.2
```

### What happened

`skip-when-tags-exist` does not use the `profile-name` parameter correctly.

I am using a user in my originating account and that user is assuming a role in my destination account. This is setup in my AWS config with a profile.

```
  prepare-aws-cli:
    description: Prepare the AWS CLI for use
    steps:
      - aws-cli/setup
      - aws-cli/setup:
          profile-name: ${AWS_PROFILE_NAME}
          role-arn: ${AWS_CIRCLECI_ROLE_ARN}
```

When I have `skip-when-tags-exist` set in `aws-ecr/build-and-push-image`, I receive an error that the user in my originating account does not have access to describe images in my destination account. It appears that is because the profile is not being used in the `aws ecr describe-images` command when `skip-when-tags-exist` is set to true, but I'm not sure why?

Even though it appears it is being set in `ecr-login` above, why is it not being respected in the command here? 

```
An error occurred (AccessDeniedException) when calling the DescribeImages operation
```

### Expected behavior

The `skip-when-tags-exist` check should use the `profile-name` parameter correctly and use the specified profile to check for existing tags.

### PR DESCRIPTION
**Pull request by duffn**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Fixes #126 

### Description

Adds `--profile` argument to `describe-images` call for `skip-when-tags-exist` so that this command does not fail when using profiles. See #126 for more detail.

### CODE REVIEW

**Comment by jozenstar** [comment]
+1

**Comment by KyleTryon** [comment]
Initiating tests

**Comment by KyleTryon** [comment]
Hello @duffin,

Thank you for your PR. It appears this should cause no adverse changes. I will mark this as a patch update and merge in.

**Review by KyleTryon — APPROVED** [review]
Tested and reviewed. Submitting as a patch update, for a bug fix.

**Pull request merged**
