### PR TITLE
[semver:minor] allow to config the remote docker version

### PR DESCRIPTION
**Pull request by ericchanky**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

[docker engine 17 is not supported](https://circleci.com/docs/2.0/building-docker-images/?mkt_tok=eyJpIjoiTnpNek1ETXpNemMzTVRGayIsInQiOiI1dzdMbGlodFF1NTZhU0t0OUsxSXNrb3BwOW8xTjVqSGhJZ29BSmU2WFpUSnlZNUEwT0hcL2xqK0I3WXZQSE82eHNzQVE0bjUrOGJTaGdlME9kRStnXC9MSENEK1NwcCtsb2M1OGlvaXVmSkdJMCtQQ2lpWjhTaWxLOFg3blRUaFlKIn0%3D#docker-version)

### CODE REVIEW

**Review by gmemstr — CHANGES_REQUESTED** [review]
[Some minor linting errors](https://app.circleci.com/pipelines/github/CircleCI-Public/aws-ecr-orb/311/workflows/5304283d-d75b-4d8f-8826-0d1318a29ae0/jobs/931), otherwise looks good! :)

**Comment by ericchanky** [comment]
oh sorry for the careless mistake, haha

**Comment by alinefr** [comment]
I didn't realize about this open PR, I've created one but i've closed it. Can we have `docker-remote-version` as a parameter also in `build-and-push-image` job? 
For reference, I've done it like this: https://github.com/CircleCI-Public/aws-ecr-orb/pull/115/commits/aef1d52e1c237ecef9a42ad9fffd23829bc2d5ef

**Comment by alinefr** [comment]
Also, one more motivation for this: https://support.circleci.com/hc/en-us/articles/360050934711

**Comment by dsayling** [comment]
Valid point!
@ericchanky can you accommodate @alinefr's request?

**Comment by ericchanky** [comment]
updated

**Review by gmemstr — APPROVED** [review]

**Pull request merged**
