### PR TITLE
Add optional lifecycle hooks

### PR DESCRIPTION
**Pull request by Tybot204**
Should resolve https://github.com/CircleCI-Public/aws-ecr-orb/issues/10

### CODE REVIEW

**Comment by iynere** [comment]
hi @Tybot204, are the `pre-steps` and `post-steps` features not sufficient for this use case ?

https://circleci.com/docs/2.0/reusing-config/#using-pre-and-post-steps

**Comment by Tybot204** [comment]
@iynere Ah I didn't see those before! I'll test it out for our use case. There may be cases where these hooks are still useful outside of my use case though.

**Comment by iynere** [comment]
@Tybot204 thanks, do that & let me know !

yeah, the only situation `pre-` and `post-steps` don't cover is, if you want to run some custom commands between `- checkout` & the rest of the job. although in that case, tbh, i'd just suggest that folks use the included orb commands, instead of the job, so they can mix & match & rearrange things themselves.

**Comment by Tybot204** [comment]
@iynere The `pre-steps` command worked for my Docker login case; thanks for the info!

That's a good point recommending to call commands directly. I wonder why the docker-publish orb decided not to go that route 🤔 I think we could close this then in favor of calling the commands directly.

**Comment by iynere** [comment]
@Tybot204 sounds good !

some orbs have commands + jobs, some have only commands, some have only jobs—depends on the use cases

& sometimes an orb _should_, but doesn't yet, provide ways to use it via both jobs _and_ commands—so if you think the `docker-publish` orb should provide a command folks can use, as well as a job, please feel free to submit a PR against the [circleci-orbs](https://github.com/circleci-public/circleci-orbs) repo where it lives 🎉

**Pull request closed without merging**
