### PR TITLE
[chore]: update images to current

### PR DESCRIPTION
**Pull request by brentmmarks**

### CODE REVIEW

**Comment by massimoplaitano** [comment]
Due to the deprecation of old images, what do you think about updating the executor also?
In `src/executors/default.yml`, there is a deprecated image: `ubuntu-2004:current`

**Comment by brentmmarks** [comment]
> src/executors/default.yml

This image is not deprecated

**Review by bjohnso5 — APPROVED** [review]

**Comment by ErkoRisthein** [comment]
Any release planned for this?

**Comment by brentmmarks** [comment]
Orb was released to address change for actual orb images in 9.0.2: https://github.com/CircleCI-Public/aws-ecr-orb/tree/v9.0.2 - this change was just for testing flow

**Pull request merged**
